version: "3.5"
services:
  db:
    image: "postgres:13-alpine"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: pamela
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  bot:
    shm_size: 1gb
    build:
      context: .
      dockerfile: Dockerfile
    command: ./script/start.sh
    env_file: .env
    image: "pamela_bot"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - "TZ=Europe/Berlin"

volumes:
  pgdata: {}
